### ISSUE TITLE
Dynamic Playlist Breaking

### ISSUE THREAD

**Issue by emilysnowflake** [ArtisTechMedia/ccMixterHost#23]
When I create a dynamic playlist using this URL:
 http://ccmixter.org/playlist/save?tags=music4healing+acappella

...the track I uploaded using the same tags in the new submit forms appears in the playlist at first. But once I change the dynamic query from 25 to 50 songs to display, the track disappears from the playlist and when I change it back, the playlist remains blank. I've duplicated the issue a few times.

**Comment by emilysnowflake** [comment]
I'm trying to narrow in on the issue. It seems once there is an edit made to the "Edit Dynamic Query" it is triggering a change in the top drop down box -- that is now adding filters that didn't exist previously? Like, it seems to limit it to Remixes. I can't remember what is was previously and I can't see it anymore. 

It seems the Types in the Dynamic Drop Down window have been altered.

**Comment by emilysnowflake** [comment]
![screen shot 2015-02-17 at 8 39 48 am](https://cloud.githubusercontent.com/assets/6187429/6232497/35f5454e-b681-11e4-8cbe-70a5adc1dd82.png)

**Comment by emilysnowflake** [comment]
i changed the system tag to music_for_healing concerned that having a number in the tag could be triggering the issue (music4healing). that doesn't seem to be the issue however.

**Comment by victor-stone** [comment]
Fixed by going to Global Settings->Query Browser and changing the reqtag from 'remix' to 'media' (which is on all uploads)

For good measure I added a cappella and sample to req tag drop down but that was not necessary.

Closing this issue - yet another case of "how did this ever work?" - in other words: this seems to have been a bug always there but uncovered by the upgrade to php5

**Comment by emilysnowflake** [comment]
Thank you for fixing this Victor! :)
