### ISSUE TITLE
Automatically resize ccMixter Avatars

### ISSUE THREAD

**Issue by emilysnowflake** [ArtisTechMedia/ccMixterHost#4]
Currently users must have a 93x93 image to upload as their ccMixter avatar, or they receive an error message. It would be wonderful if ccMixter could resize the image for the user, more like other social media sites. We can still provide parameters for optimal image resize, dimensions, etc.

**Comment by victor-stone** [comment]
I think the thing to do here is exec imagemagick from the 'nix command. However since a generic ccHost installation (remember the license agreement with CC requires us to not break ccHost) I the following has to happen:

-1) Install imagemagick on the server if it's not there
1) add an admin global path property called 'path-to-imagemagick' 
2) in the current upload code, check for the path. If there, exec() it with resize parameters. If not, execute the current code

In anticipation of more/pretty user profiles, we'll keep the larger image around.

The real task here will be testing against all the infinite number of image types and sizes that will be thrown at us.
